input.onButtonPressed(Button.A, function () {
    startbit.setServo(startbit.startbit_servorange.range2, 1, 160, 500)
    startbit.startbit_setPixelRGB(StartbitLights.Light1, StartbitRGBColors.Red)
    startbit.startbit_setPixelRGB(StartbitLights.Light2, StartbitRGBColors.Green)
    startbit.startbit_showLight()
    basic.pause(500)
    startbit.startbit_showLight()
    basic.pause(500)
    startbit.setServo(startbit.startbit_servorange.range2, 1, 110, 50)
    startbit.startbit_clearLight()
    basic.pause(500)
})
startbit.startbit_Init()
basic.pause(500)
startbit.setServo(startbit.startbit_servorange.range2, 1, 160, 500)
basic.pause(500)
